// Products Actions
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const SET_CURRENT_PRODUCT = "SET_CURRENT_PRODUCT";

// Cart Actions
export const SET_PRODUCT_CART = "SET_PRODUCT_CART";
export const CHANGE_STATE_CART = "CHANGE_STATE_CART";
export const INCREASE_PRODUCT_CART = "INCREASE_PRODUCT_CART";
export const DECREASE_PRODUCT_CART = "DECREASE_PRODUCT_CART";
export const DELETE_PRODUCT_CART = "DELETE_PRODUCT_CART";
